name: Dev.to Publish
on: [push]
jobs:
  crosspost:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - uses: basicBrogrammer/crosspost-markdown@v0.1
      with:
        content-dir: './content/articles/'
        dev-to-token: 'funny-funny'
